apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inno-microservices
resources:
  - ../../base
patches:
  - path: patches/api-gateway-replicas.yaml
  - path: patches/auth-replicas.yaml
  - path: patches/order-replicas.yaml
  - path: patches/payment-replicas.yaml
  - path: patches/user-replicas.yaml