apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: inno-microservices
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 20

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: AUTH_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: DB_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data

  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi