services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - inno-microservices-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    networks:
      - inno-microservices-network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - 9080:9080
    environment:
      GRAFANA_LOKI_URL: http://loki:3100/loki/api/v1/push
    command:
      - run
      - /etc/alloy/config.alloy
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    networks:
      - inno-microservices-network
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - 3200:3200
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./monitoring/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-data:/var/tempo
    networks:
      - inno-microservices-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - inno-microservices-network

  auth-db:
    image: postgres:latest
    container_name: auth-service-database
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${AUTH_DB_PORT}:5432
    volumes:
      - auth-service-database-data:/var/lib/postgresql
    networks:
      - inno-microservices-network

  user-db:
    image: postgres:latest
    container_name: user-service-database
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${USER_DB_PORT}:5432
    volumes:
      - user-service-database-data:/var/lib/postgresql
    networks:
      - inno-microservices-network

  order-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${ORDER_DB_PORT}:5432
    volumes:
      - order-service-database-data:/var/lib/postgresql
    networks:
      - inno-microservices-network

  payment-db:
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      volumes:
        - mongo:/data/db
      ports:
        - ${MONGODB_PORT}:27017
      networks:
        - inno-microservices-network

  kafka:
    image: apache/kafka-native:latest
    environment:
      - CLUSTER_ID='LOCAL'
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=1
    ports:
      - ${KAFKA_PORT}:9092
    networks:
      - inno-microservices-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - inno-microservices-network

  auth-service:
    build:
      context: ./auth-service/auth-service
    container_name: authentication-service
    ports:
      - ${AUTH_SERVICE_PORT}:8000
    environment:
      DB_URL: ${AUTH_DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: ${AUTH_SERVICE_PORT}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
    depends_on:
      - auth-db
      - alloy
    networks:
      - inno-microservices-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service-rest
    ports:
      - ${USER_SERVICE_PORT}:8081
    environment:
      SPRING_DATASOURCE_URL: ${USER_DB_URL}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AUTH_SERVICE_URL: http://auth-service:${AUTH_SERVICE_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${USER_SERVICE_PORT}
    depends_on:
      - user-db
      - auth-service
      - redis
      - alloy
    networks:
      - inno-microservices-network

  order-service:
    build:
      context: ./order-service
    container_name: order-service-1
    ports:
      - ${ORDER_SERVICE_PORT}:8082
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: ${ORDER_DB_URL}
      AUTH_SERVICE_URL: http://auth-service:${AUTH_SERVICE_PORT}
      USER_SERVICE_URL: http://user-service:${USER_SERVICE_PORT}
      CONSUMER_GROUP_ID: ${ORDER_CONSUMER_GROUP_ID}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      SERVER_PORT: ${ORDER_SERVICE_PORT}
    depends_on:
      - order-db
      - kafka
      - auth-service
      - user-service
      - alloy
    networks:
      - inno-microservices-network

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - ${PAYMENT_SERVICE_PORT}:8084
    environment:
      EXTERNAL_API_URL: ${EXTERNAL_API_URL}
      SERVER_PORT: ${PAYMENT_SERVICE_PORT}
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      CONSUMER_GROUP_ID: ${CONSUMER_GROUP_ID}
      MONGODB_URI: ${MONGODB_URI}
      KAFKA_PORT: ${KAFKA_PORT}
    depends_on:
      - payment-db
      - kafka
      - auth-service
      - user-service
      - order-service
      - alloy
    networks:
      - inno-microservices-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - ${API_GATEWAY_PORT}:8080
    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL}
      AUTH_CLIENT_URL: ${AUTH_CLIENT_URL}
      SERVER_PORT: ${API_GATEWAY_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service
      - alloy
    networks:
      - inno-microservices-network

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-database
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - ${KC_DB_PORT}:5432
    networks:
      - inno-microservices-network
    volumes:
      - keycloak-db-data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-server
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    ports:
      - ${KC_PORT}:8080
    depends_on:
      - keycloak-db
    networks:
      - inno-microservices-network

volumes:
  auth-service-database-data:
  user-service-database-data:
  order-service-database-data:
  redis-data:
  mongo:
  grafana-storage:
  loki-data:
  tempo-data:
  keycloak-db-data:

networks:
  inno-microservices-network:
    driver: bridge