server:
  port: ${SERVER_PORT}

spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/api/v1/auth/**

            - id: user-service
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - AuthenticationFilter

            - id: order-service
              uri: ${ORDER_SERVICE_URL}
              predicates:
                - Path=/api/v1/orders/**
auth-client:
  url: ${AUTH_CLIENT_URL}