apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: inno-microservices
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: REDIS_PASSWORD

          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20

          volumeMounts:
            - mountPath: /data
              name: redis-data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 500Mi