apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: inno-microservices
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: wait-for-services
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z auth-service 8000; do echo "waiting auth"; sleep 2; done &&
              until nc -z user-service 8081; do echo "waiting user"; sleep 2; done &&
              until nc -z order-service 8082; do echo "waiting order"; sleep 2; done &&
              until nc -z payment-service 8084; do echo "waiting payment"; sleep 2; done
      containers:
        - name: api-gateway
          imagePullPolicy: IfNotPresent
          image: inno-microservices-api-gateway:latest
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20

          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: USER_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: ORDER_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: PAYMENT_SERVICE_URL