spring:
  application:
    name: 'auth-service'
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: innocourse
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
server:
  port: 8080
jwt:
  secret: a4d877da4c158ef516877d2edb38d5035bd33fc0d2181a1557f22542036a5d98
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 86400000