spring:
  application:
    name: 'auth-service'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
  docker:
    compose:
      enabled: true
      file: .\auth-service\auth-service\docker-compose.yml
server:
  port: ${SERVER_PORT}
jwt:
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 86400000
user-service:
  url: ${USER_SERVICE_URL}