version: '3.9'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - ${SERVER_PORT}:8082
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: order-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - order-service-db-data:/var/lib/postgresql/data

volumes:
  order-service-db-data: