version: '3.9'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
#    ports:
#      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orders_db
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: order-service-db
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: innocourse
    ports:
      - "5433:5432"
    volumes:
      - order-service-db-data:/var/lib/postgresql/data

volumes:
  order-service-db-data: