apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: inno-microservices
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        - name: wait-for-order-db-and-kafka
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z order-db 5432; do echo "waiting order-db"; sleep 2; done &&
              until nc -z kafka 9092; do echo "waiting kafka"; sleep 2; done
      containers:
        - name: order-service
          imagePullPolicy: IfNotPresent
          image: inno-microservices-order-service:latest
          ports:
            - containerPort: 8082

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 20

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: ORDER_DB_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: USER_SERVICE_URL
            - name: CONSUMER_GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: ORDER_CONSUMER_GROUP_ID
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-environment
                  key: KAFKA_BOOTSTRAP_SERVERS