spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${CONSUMER_GROUP_ID}
  docker:
    compose:
      enabled: true
      file: .\user-service\docker-compose.yml

server:
  port: ${SERVER_PORT}

external-api:
  url: ${EXTERNAL_API_URL}
