spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

server:
  port: ${SERVER_PORT}

external-api:
  url: {EXTERNAL_API_URL}
