apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: inno-microservices
  labels:
    app: order-db
spec:
  selector:
    app: order-db
  ports:
   - port: 5432
     name: postgres
  clusterIP: None