spring:
  application:
    name: 'user-service'
  datasource:
    url: jdbc:postgresql://localhost:5432/userdatadb
    username: postgres
    password: innocourse
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate