spring:
  application:
    name: 'user-service'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cache:
    type: redis
server:
  port: ${SERVER_PORT}

management:
  endpoint:
    health:
      probes:
        enabled: true