services:
  db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - auth-service-db-data:/var/lib/postgresql/data

volumes:
  auth-service-db-data: