version: '3.9'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - ${SERVER_PORT}:8000
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - auth-service-db-data:/var/lib/postgresql/data

volumes:
  auth-service-db-data: