version: '3.9'

services:
  user-service:
    build: .
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auth_db
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: auth-service-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: innocourse
    ports:
      - "5432:5432"
    volumes:
      - auth-service-db-data:/var/lib/postgresql/data

volumes:
  auth-service-db-data: