spring:
  application:
    name: 'order-service'
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: innocourse
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080