spring:
  application:
    name: 'order-service'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: ${SERVER_PORT}

user-service:
    url: ${USER_SERVICE_URL}