apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
  namespace: inno-microservices
  labels:
    app: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017

          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 20

          volumeMounts:
            - mountPath: /data/db
              name: mongo-data

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-environment
                  key: MONGODB_PASSWORD
            - name: MONGODB_INITDB_DATABASE
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi