version: '3.9'

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - ${SERVER_PORT}:8081
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - user-service-redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  user-service-db-data:
  user-service-redis-data: