version: '3.9'

services:
  user-service:
    build: .
    container_name: user-service
#    networks:
#      - backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdatadb
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: userdatadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: innocourse
    ports:
      - "5432:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_
    ports:
      - "6379:6379"
    volumes:
      - user-service-redis-data:/data
    environment:
      - REDIS_PASSWORD=12345

volumes:
  user-service-db-data:
  user-service-redis-data: