version: '3.9'

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_
    ports:
      - "6379:6379"
    volumes:
      - user-service-redis-data:/data

volumes:
  user-service-db-data:
  user-service-redis-data:
