name: CI Pipeline Order

on:
  push:
    branches:
      - master
      - orderservice
  pull_request:

defaults:
  run:
    working-directory: order-service

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: innocourse
          POSTGRES_DB: orders_db
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build project
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: order-service-build-artifacts
          path: |
            order-service/target/classes/
            order-service/target/test-classes/
            order-service/target/*.jar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: innocourse
          POSTGRES_DB: orders_db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: order-service-build-artifacts
          path: order-service/target
          merge-multiple: true

      - name: Run tests
        env:
          USER_SERVICE_URL: http://user-service:8081
        run: |
          chmod +x mvnw
          ./mvnw test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: order-service-test-artifacts
          path: |
            order-service/target/surefire-reports/  


  sonar:
    name: Code Analysis (SonarQube)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: order-service-build-artifacts
          path: order-service/target
          merge-multiple: true

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: order-service-test-artifacts
          path: order-service/target
          merge-multiple: true

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x mvnw
          ./mvnw sonar:sonar
